# config for train.py

## ───────────────────────────────────── ▼ ─────────────────────────────────────
# {{{                           --     Init    --
#···············································································
[[init]]
wandb_project = 'MMT-v2'
output_dir = 'en-ru-outdir'
model_checkpoint = 'google/mt5-xl'
en_ru ='ru-en-mt5-xl'
#dataset_name = 'wmt14'
#lang_pairs = ['fr-ru']
max_seq_length = 96
preprocessing_num_workers = 8
split = 'None'
all_langs=false
#                                                                            }}}
## ─────────────────────────────────────────────────────────────────────────────



## ───────────────────────────────────── ▼ ─────────────────────────────────────
# {{{                             --    Training Args      --
#···············································································
[[train]]
batch_size = 8 
accum_iter = 16
learning_rate = 4e-3
weight_decay = 0.00
dropout_rate = 0.0
num_train_epochs = 3
eval_every_steps = 20000
logging_steps = 10
max_train_steps = 0
lr_scheduler_type = 'linear'
num_warmup_steps = 5000
beam_size = 4
seed = 'None'
#                                                                            }}}
## ─────────────────────────────────────────────────────────────────────────────




